- test_deepmove.py
- trafficdl/data/dataset/trajectory_dataset.py
- trafficdl/evaluator/eval_funcs.py
- trafficdl/evaluator/traj_loc_pred_evaluator.py
- trafficdl/executor/traj_loc_pred_executor.py
> Jwj refactor TrajLocPredEvaluator

- .gitignore
- trafficdl/data/batch.py
- trafficdl/data/dataset/__init__.py
- trafficdl/data/dataset/traffic_speed_dataset.py
- trafficdl/data/utils.py
- trafficdl/utils/utils.py
batch 
to_tensor()函数从LongTensor改成FloatTensor
data/util
generate_dataloader() 增加参数pad_with_last_sample，控制最后一个batch长度的补齐
util/util
增加get_logger()以使用log，保存路径为trafficdl/log/...
使用方法：
1.在test_model.py中初始化一次logger = get_logger(config)。
2.在想要使用log的文件中from logging import getLogger，之后self.logger=getLogger()即可。
> 修改一些utils和batch

- .gitignore
- test_dcrnn.py
- trafficdl/evaluator/__init__.py
- trafficdl/evaluator/traffic_speed_pred_evaluator.py
- trafficdl/executor/__init__.py
- trafficdl/executor/traffic_speed_pred_executor.py
- trafficdl/model/__init__.py
- trafficdl/model/init.py
- trafficdl/model/layers.py
- trafficdl/model/loss.py
- trafficdl/model/traffic_speed_prediction/DCRNN.py
Traffic speed pred的evaluator/executor/test
Model-DCRNN
> Traffic speed pred init

- libtraffic/config/evaluator/TrafficStateEvaluator.json
- libtraffic/data/dataset/traffic_state_datatset.py
- libtraffic/evaluator/traffic_state_evaluator.py
- libtraffic/model/traffic_flow_prediction/ASTGCN.py
- libtraffic/model/traffic_flow_prediction/ASTGCNCommon.py
- libtraffic/model/traffic_flow_prediction/MSTGCN.py
- libtraffic/model/traffic_flow_prediction/MSTGCNCommon.py
FIX BUG in ASTGCN MSTGCN
evaluator add save_modes(csv, json)
> Fix astgcn

- readme_zh.md
> fix readme

- requirements.txt
> fix ray tune in requirements

- libcity/config/task_config.json
Reverts LibCity/Bigscity-LibCity#224
> Revert "fix task_config.json"

- libcity/data/dataset/traffic_state_datatset.py
> fix load rel

- libcity/data/dataset/trajectory_encoder/serm_encoder.py
> add serm vecpath not found error

- libcity/config/evaluator/CARALocPredEvaluator.json
- libcity/data/dataset/trajectory_encoder/__init__.py
- libcity/data/dataset/trajectory_encoder/cara_encoder.py
- libcity/data/dataset/trajectory_encoder/strnn_encoder.py
- libcity/evaluator/cara_loc_pred_evaluator.py
- libcity/model/trajectory_loc_prediction/CARA.py
> fix STRNN and CARA error

- libcity/utils/visualize.py
support bj_roadmap_edge bj_roadmap_node and Chengdu_Taxi_Sample1
> fix VisHelper

- libcity/data/dataset/dataset_subclass/__init__.py
- libcity/model/road_representation/LINE.py
- libcity/model/road_representation/__init__.py
> fix import in init

- libcity/config/model/traj_loc_pred/HSTLSTM.json
- libcity/config/model/traj_loc_pred/STAN.json
- libcity/data/dataset/trajectory_dataset.py
- libcity/data/dataset/trajectory_encoder/stan_encoder.py
- libcity/model/trajectory_loc_prediction/HSTLSTM.py
* Fix HSTLSTM loss function error.
* Fix trajectory dataset cutter_filter index bug.
* Update STAN config file
> Fix some bug in traj loc pred

- libcity/data/batch.py
- libcity/data/dataset/dataset_subclass/pbs_trajectory_dataset.py
- libcity/data/dataset/eta_dataset.py
- libcity/data/dataset/trajectory_dataset.py
- libcity/data/utils.py
把不需要补齐的batch跟需要补齐的batch分开了，增加可读性
> simple_batch

- libcity/evaluator/traj_loc_pred_evaluator.py
- libcity/executor/traj_loc_pred_executor.py
> delete tqdm from executor and add some logger

- libcity/evaluator/traj_loc_pred_evaluator.py
> fix log info bug in traj_loc_pred_evaluator

- libcity/model/trajectory_loc_prediction/STAN.py
The bug is that we fix parameter "max_session_len" in privious commit, but forgget to adjust the STAN which uses this parameter.
> fix STAN bug

- libcity/model/traffic_speed_prediction/GTS.py
> fix bug in GTS

- libcity/config/model/traffic_state_pred/HGCN.json
- libcity/data/dataset/dataset_subclass/hgcn_dataset.py
- libcity/model/traffic_speed_prediction/HGCN.py
> fix bug in HGCN

- libcity/data/dataset/trajectory_encoder/hstlstm_encoder.py
Closes #327 
修改该 issue 发现的 Bug
> fix time interval init value error in HstlstmEncoder

- libcity/config/model/traj_loc_pred/DeepMove.json
- libcity/data/dataset/trajectory_encoder/serm_encoder.py
* update the config of the DeepMove (remove max_session_len param)
* fix SERM's traj encoder cannot process on foursquare_tky dataset.
> Jwj fix serm

- libcity/config/evaluator/TrajLocPredEvaluator.json
- libcity/evaluator/traj_loc_pred_evaluator.py
- libcity/executor/traj_loc_pred_executor.py
您好，我在完成一项关于提交pr的课程作业，需要向开源项目提交一次pr，结合我在使用libcity的体验创建了这次pr，如有打扰，烦请见谅。
该次修改实现了轨迹预测时可以一次性评测多个topk的值，需要将config中相应tok的值改为类似于[1,5,10]的list，也可只保留单个值类似1这种。
> 实现一次评测多个tok的值

- libcity/config/data/DSTAGNNDataset.json
- libcity/config/model/traffic_state_pred/DSTAGNN.json
- libcity/config/task_config.json
- libcity/data/dataset/dataset_subclass/__init__.py
- libcity/data/dataset/dataset_subclass/dstagnn_dataset.py
- libcity/model/loss.py
- libcity/model/traffic_flow_prediction/DSTAGNN.py
- libcity/model/traffic_flow_prediction/__init__.py
数据集文件配置（DSTAGNNDataset.json），跑 PEMSD4 数据集时要调整 batch_size 参数为 32
```json
{
"batch_size": 64,
"train_rate": 0.6,
"eval_rate": 0.2,
"load_external": false,
"input_window": 12,
"sparsity": 0.01,
"period": 288
}
```
模型参数配置（DSTAGNN.json）
```json
{
"max_epoch": 100,
"learner": "adam",
"learning_rate": 0.0001,
"use_early_stop": false,
"in_channels": 1,
"nb_block": 4,
"K": 3,
"nb_chev_filter": 32,
"nb_time_filter": 32,
"d_model": 512,
"d_k": 32,
"n_heads": 3,
"graph_use": "AG"
}
```
模型评价指标对比如下，DSTAGNN 的指标是使用原论文代码本地复现的结果
- PEMSD4
| PEMSD4 | LibCity | DSTAGNN |
| ---- | ---- | ---- |
|  MAE |  19.63 | 19,28 |
| RMSE |  31.89 |  31.37 |
| MAPE |  13.15% |  12.72% |
- …
> Add model DSTAGNN

- libcity/config/data/SimSTDataset.json
- libcity/config/model/traffic_state_pred/SimST.json
- libcity/config/task_config.json
- libcity/data/dataset/dataset_subclass/__init__.py
- libcity/data/dataset/dataset_subclass/simst_dataset.py
- libcity/model/traffic_flow_prediction/SimST.py
- libcity/model/traffic_flow_prediction/__init__.py
数据集配置文件（SimSTDataset.json）
```json
{
"batch_size": 1024,
"pad_with_last_sample": true,
"train_rate": 0.6,
"eval_rate": 0.2,
"load_external": true,
"input_window": 12,
"add_time_in_day": true,
"add_day_in_week": true,
"normalized_k": 0,
"in_neighbor_num": 0,
"infer_bs": 64
}
```
模型配置文件（SimST.json）
```json
{
"max_epoch": 150,
"learner": "adam",
"learning_rate": 0.001,
"weight_decay": 0.0001,
"lr_decay": true,
"lr_scheduler": "ReduceLROnPlateau",
"lr_decay_ratio": 0.31622776601683794,
"lr_patience": 10,
"clip_grad_norm": true,
"max_grad_norm": 5,
"use_early_stop": true,
"patience": 20,
"node_dim": 20,
"in_dim": 5,
"init_dim": 64,
"end_dim": 512,
"layer": 2, …
```
> Add model SimST

- libcity/config/executor/TimeMixerExecutor.json
- libcity/config/model/traffic_state_pred/TimeMixer.json
- libcity/config/task_config.json
- libcity/executor/__init__.py
- libcity/executor/timemixer_executor.py
- libcity/model/traffic_flow_prediction/TimeMixer.py
- libcity/model/traffic_flow_prediction/__init__.py
数据集配置文件（TrafficStatePointDataset.json）
```json
{
"batch_size": 32,
"pad_with_last_sample": true,
"train_rate": 0.6,
"eval_rate": 0.2,
"load_external": false,
"input_window": 96,
"add_time_in_day": false,
"add_day_in_week": false
}
```
模型配置文件（TimeMixer.json）
```json
{
"label_len": 0,
"down_sampling_layers": 1,
"down_sampling_window": 2,
"down_sampling_method": "avg",
"channel_independence": 0,
"e_layers": 5,
"d_model": 128,
"d_ff": 256,
"use_norm": 0,
"freq": "h",
"embed": "timeF",
"decomp_method": "moving_avg",
"moving_avg": 25,
"dropout": 0.1
}
```
执行器配置信息（TimeMixerExecutor.json）
```json
{
"gpu": true,
"gpu_id": 0,
"max_epoch": 10,
"train_loss": "none", …
```
> Add model TimeMixer

- libcity/config/data/TrafficStateDataset.json
- libcity/config/data/TrafficStatePointDataset.json
- libcity/data/dataset/traffic_state_datatset.py
- libcity/utils/__init__.py
- libcity/utils/disturbance.py
PEMSD8-flow数据(均值230，标准差145)，均值10标准差500噪声，HIEST模型结果
噪声比例 | MAE | RMSE
-- | -- | --
0 | 15.07 | 23,83
0.1 | 34.79 | 59.92
0.3 | 82.70 | 119.62
0.9 | 163.58 | 201.03
PEMSD8-flow数据(均值230，标准差145)，均值10标准差15噪声，HIEST模型结果
噪声比例 | MAE | RMSE | MAPE
-- | -- | -- | --
0 | 15.04 | 23.88 | 9.77%
0.1 | 15.18 | 23.97 | 10.40%
0.2 | 15.34 | 24.09 | 11.05%
0.3 | 15.56 | 24.25 | 11.79%
设置零值结果
噪声比例 | MAE | RMSE | MAPE
-- | -- | -- | --
0 | 15.04 | 23.88 | 9.77%
0.1 | 23.26 | 37.41 | 13.19%
0.2 | 31.09 | 48.31 | 17.24%
0.3 | 38.28 | 58.46 | 20.85%
> Robustness test

- libcity/config/executor/MegaCRNExecutor.json
- libcity/config/model/traffic_state_pred/MegaCRN.json
- libcity/config/task_config.json
- libcity/executor/__init__.py
- libcity/executor/megacrn_executor.py
- libcity/model/traffic_speed_prediction/MegaCRN.py
- libcity/model/traffic_speed_prediction/__init__.py
数据集配置文件（TrafficStatePointDataset.json）
```json
{
"batch_size": 64,
"pad_with_last_sample": true,
"train_rate": 0.7,
"eval_rate": 0.1,
"load_external": true,
"input_window": 12,
"add_time_in_day": true,
"add_day_in_week": false
}
```
模型配置文件（MegaCRN.json）
```json
{
"rnn_units": 64,
"num_layers": 1,
"cheb_k": 3,
"ycov_dim": 1,
"cl_decay_steps": 2000,
"use_curriculum_learning": true,
"mem_num": 20,
"mem_dim": 64,
"lamb": 0.01,
"lamb1": 0.01
}
```
执行器配置信息（MegaCRNExecutor.json）
```json
{
"max_epoch": 200,
"learner": "adam",
"learning_rate": 0.01,
"lr_epsilon": 0.001,
"lr_decay": true,
"lr_scheduler": "multisteplr",
"lr_decay_ratio": 0.1,
"milestones": [50,100], …
```
> feat: add Model MegaCRN

- libcity/config/data/STWaveDataset.json
- libcity/config/model/traffic_state_pred/STWave.json
- libcity/config/task_config.json
- libcity/data/dataset/dataset_subclass/__init__.py
- libcity/data/dataset/dataset_subclass/stwave_dataset.py
- libcity/model/traffic_flow_prediction/STWave.py
- libcity/model/traffic_flow_prediction/__init__.py
数据集配置文件（STWaveDataset.json）
```json
{
"batch_size": 64,
"pad_with_last_sample": false,
"train_rate": 0.6,
"eval_rate": 0.2,
"load_external": false,
"input_window": 12,
"add_time_in_day": false,
"add_day_in_week": false,
"normalized_k": 0
}
```
模型配置文件（STWave.json）
```json
{
"max_epoch": 200,
"learner": "adam",
"learning_rate": 0.001,
"lr_decay": true,
"lr_scheduler": "ReduceLROnPlateau",
"lr_decay_ratio": 0.1,
"lr_patience": 20,
"lr_threshold": 0.001,
"clip_grad_norm": true,
"max_grad_norm": 5,
"use_early_stop": false,
"heads": 8,
"dims": 16,
"layers": 2,
"samples": 1,
"wave": "coif1",
"level": 1
}
```
执行器配置信息（TrafficStateExecutor.json）
```json
{
"gpu": true, …
```
> feat: add Model STWave

- libcity/config/model/traffic_state_pred/STGNCDE.json
- libcity/config/task_config.json
- libcity/model/traffic_flow_prediction/STGNCDE.py
- libcity/model/traffic_flow_prediction/__init__.py
| PEMSD4 | libcity | STG-NCDE |
| ------ | ------- | -------- |
| MAE:   | 19.89   | 19.78    |
| RMSE:  | 31.58   | 31.6     |
| MAPE:  | 13.84%  | 13.55%   |
> STGNCDE update
